sudo: required
service :
  - docker


before_install :
  - docker build -t docker-react -f Dockerfile.dev .

script :
  # - docker run docker-react npm run build
  - docker run docker-react npm run test -- --coverage

deploy : 
  provider : elasticbeanstalk
  region : us-east-1
  app : Docker-React%20POC
  env : DockerReactPoc-env
  bucket_name : elasticbeanstalk-us-east-1-438985684090
  bucket_path :  Docker-React%20POC
  on :
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure : "$AWS_SECRET_KEY"
  